# melpazoid <https://github.com/riscy/melpazoid> build checks.

# If your package is on GitHub, enable melpazoid's checks by copying this file
# to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.
---
name: melpazoid
'on': [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - 30.1
          - release-snapshot
    steps:
      - name: Get repo to access in conteiner
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip
          # sudo apt-get install emacs-nox  && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Tests async
        run: |
         emacs -Q --batch -l ert.el -l oai-async1.el -l ./tests/oai-tests-async1.el -f ert-run-tests-batch-and-exit
      - name: Tests timers
        run: |
         emacs -Q --batch -l ert.el -l oai-timers.el -l ./tests/oai-tests-timers.el -f ert-run-tests-batch-and-exit
      - name: Tests block
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-block.el -l ./tests/oai-tests-block.el -f ert-run-tests-batch-and-exit
      - name: Tests block tags
        run: |
         git clone --depth=1 https://github.com/Anoncheg1/emacs-org-links.git
         emacs -Q --batch -l ert.el -l oai-debug.el -l ./emacs-org-links/org-links.el -l oai-block.el -l oai-block-tags.el -l ./tests/oai-tests-block-tags.el -f ert-run-tests-batch-and-exit
      - name: Tests restapi
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-block.el -l oai-block-tags.el -l oai-timers.el -l oai-async1.el -l oai-restapi.el -l ./tests/oai-tests-restapi.el -f ert-run-tests-batch-and-exit
      - name: Tests optional
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-optional.el -l ./tests/oai-tests-optional.el -f ert-run-tests-batch-and-exit
      - name: Tests prompt
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-block.el -l oai-block-tags.el -l oai-timers.el -l oai-async1.el -l oai-restapi.el -l oai-prompt.el -l ./tests/oai-tests-prompt.el -f ert-run-tests-batch-and-exit
      - name: Tests integ
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-block.el -l ./tests/oai-tests-block.el -l oai-block-tags.el -l oai-timers.el -l oai-async1.el -l oai-restapi.el -l oai-prompt.el -l oai.el -l ./tests/oai-tests-integ.el -f ert-run-tests-batch-and-exit
      - name: Tests integllm
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-block.el -l oai-block-tags.el -l oai-timers.el -l oai-async1.el -l oai-restapi.el -l oai-prompt.el -l oai.el -l ./tests/oai-tests-integllm.el -f ert-run-tests-batch-and-exit
      - name: Tests oai
        run: |
         emacs -Q --batch -l ert.el -l oai-debug.el -l oai-block.el -l oai-block-tags.el -l oai-timers.el -l oai-async1.el -l oai-restapi.el -l oai-prompt.el -l oai.el -l ./tests/oai-tests-oai.el -f ert-run-tests-batch-and-exit
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          # RECIPE is your recipe as written for MELPA:
          RECIPE: (oai :fetcher github :repo "Anoncheg1/emacs-oai")
          # set this to false (or remove it) if the package isn't on MELPA:
          EXIST_OK: true
        run: |
          echo $GITHUB_REF
          make -C ~/melpazoid |& tee output.log
          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
          if grep -q "Warning" output.log ; then
            echo "Warnings detected, failing workflow" ; exit 1
          fi
          if grep -q ': error: ' output.log ; then
            echo "Error detected, failing workflow" ; exit 1
          fi
          if grep -q ' with [melpazoid]' output.log ; then
            echo "Melpazoid warning detected, failing workflow" ; exit 1
          fi
          if grep -q ' with package-lint ' output.log ; then
            echo "Checkdoc warning detected, failing workflow" ; exit 1
          fi
          if grep -q ' with checkdoc ' output.log ; then
            echo "Checkdoc warning detected, failing workflow" ; exit 1
          fi
